### PR TITLE
#408 add support for PKCS#8 private key generated by newer versions of openssl

### PR DESCRIPTION
**Pull request by sbaeurle**
see #408

### CODE REVIEW

**Comment by vancluever** [comment]
@sbaeurle thanks for this! Can you add a test for this in `acme_structure_test.go`? 

You should be able to add this by way of a variant of `TestACME_expandACMEUser` that expands `registrationResourceData` off of the PKCS#8 key versus the old PKCS#1 key.

Thanks!

**Comment by sbaeurle** [comment]
@vancluever i left the current test case as is and simply added a new one. hope this is in line with what you intended

**Comment by vancluever** [comment]
Thanks @sbaeurle, I just adjusted the tests to fix them and make the naming more idiomatic. They pass locally, so just waiting for them to pass here and then I'll merge!

**Comment by vancluever** [comment]
Looks good, merging!

**Pull request merged**
